exports.trackhtml = '<html><head></head><body><table class="cloudcast-sections-table" id="cloudcast-sections-table" cellspacing="0"><tbody><tr class="section-row-track player-section-playing"><td class="tracklistcell"><a title="Go to track page for: 1/U = Daven’T Nay" href="/track/radioactive-man/1u-davent-nay/" class="tracklisttrackname mx-link">1/U = Daven’T Nay</a><div data-url="/track/radioactive-man/1u-davent-nay/buylinks/" class="mx-link tracklistbuylinks">Buy</div><div class="clearit"></div><span class="buylinks-placeholder"></span><div class="clearit"></div><div class="clearit"></div><a title="Go to artist page for: Radioactive Man" href="/artist/radioactive-man/" class="tracklistartistname mx-link">Radioactive Man</a><div class="clearit"></div></td><td class="section-number-cell">' +
'1' +
'</td></tr><tr class="section-row-track"><td class="tracklistcell"><a title="Go to track page for: Future Funked" href="/track/signal-type/future-funked/" class="tracklisttrackname mx-link">Future Funked</a><div data-url="/track/signal-type/future-funked/buylinks/" class="mx-link tracklistbuylinks">Buy</div><div class="clearit"></div><span class="buylinks-placeholder"></span><div class="clearit"></div><div class="clearit"></div><a title="Go to artist page for: Signal Type" href="/artist/signal-type/" class="tracklistartistname mx-link">Signal Type</a><div class="clearit"></div></td><td class="section-number-cell">' +
'2' +
'</td></tr><tr class="section-row-track"><td class="tracklistcell"><a title="Go to track page for: Communication To None" href="/track/moon-disco/communication-to-none/" class="tracklisttrackname mx-link">Communication To None</a><div data-url="/track/moon-disco/communication-to-none/buylinks/" class="mx-link tracklistbuylinks">Buy</div><div class="clearit"></div><span class="buylinks-placeholder"></span><div class="clearit"></div><div class="clearit"></div><a title="Go to artist page for: Moon Disco" href="/artist/moon-disco/" class="tracklistartistname mx-link">Moon Disco</a><div class="clearit"></div></td><td class="section-number-cell">' +
'3' +
'</td></tr><tr class="section-row-track"><td class="tracklistcell"><a title="Go to track page for: Resynth" href="/track/sync-24/resynth/" class="tracklisttrackname mx-link">Resynth</a><div data-url="/track/sync-24/resynth/buylinks/" class="mx-link tracklistbuylinks">Buy</div><div class="clearit"></div><span class="buylinks-placeholder"></span><div class="clearit"></div><div class="clearit"></div><a title="Go to artist page for: Sync 24" href="/artist/sync-24/" class="tracklistartistname mx-link">Sync 24</a><div class="clearit"></div></td><td class="section-number-cell">' +
'4' +
'</td></tr><tr class="section-row-track"><td class="tracklistcell"><a title="Go to track page for: Sonic Beatz Iii" href="/track/omega-2/sonic-beatz-iii/" class="tracklisttrackname mx-link">Sonic Beatz Iii</a><div data-url="/track/omega-2/sonic-beatz-iii/buylinks/" class="mx-link tracklistbuylinks">Buy</div><div class="clearit"></div><span class="buylinks-placeholder"></span><div class="clearit"></div><div class="clearit"></div><a title="Go to artist page for: Omega 2" href="/artist/omega-2/" class="tracklistartistname mx-link">Omega 2</a><div class="clearit"></div></td><td class="section-number-cell">' +
'5' +
'</td></tr><tr class="section-row-track"><td class="tracklistcell"><a title="Go to track page for: Substorm (Sync 24 Remix) " href="/track/scape-one/substorm-sync-24-remix/" class="tracklisttrackname mx-link">Substorm (Sync 24 Remix) </a><div data-url="/track/scape-one/substorm-sync-24-remix/buylinks/" class="mx-link tracklistbuylinks">Buy</div><div class="clearit"></div><span class="buylinks-placeholder"></span><div class="clearit"></div><div class="clearit"></div><a title="Go to artist page for: Scape One" href="/artist/scape-one/" class="tracklistartistname mx-link">Scape One</a><div class="clearit"></div></td><td class="section-number-cell">' +
'6' +
'</td></tr><tr class="section-row-track"><td class="tracklistcell"><a title="Go to track page for: Forest Communication" href="/track/alpha-606-sync-24/forest-communication/" class="tracklisttrackname mx-link">Forest Communication</a><div data-url="/track/alpha-606-sync-24/forest-communication/buylinks/" class="mx-link tracklistbuylinks">Buy</div><div class="clearit"></div><span class="buylinks-placeholder"></span><div class="clearit"></div><div class="clearit"></div><a title="Go to artist page for: Alpha 606 &amp; Sync 24" href="/artist/alpha-606-sync-24/" class="tracklistartistname mx-link">Alpha 606 &amp; Sync 24</a><div class="clearit"></div></td><td class="section-number-cell">' +
'7' +
'</td></tr><tr class="section-row-track"><td class="tracklistcell"><a title="Go to track page for: Conveyor" href="/track/matt-whitehead/conveyor/" class="tracklisttrackname mx-link">Conveyor</a><div data-url="/track/matt-whitehead/conveyor/buylinks/" class="mx-link tracklistbuylinks">Buy</div><div class="clearit"></div><span class="buylinks-placeholder"></span><div class="clearit"></div><div class="clearit"></div><a title="Go to artist page for: Matt Whitehead" href="/artist/matt-whitehead/" class="tracklistartistname mx-link">Matt Whitehead</a><div class="clearit"></div></td><td class="section-number-cell">' +
'8' +
'</td></tr><tr class="section-row-track"><td class="tracklistcell"><a title="Go to track page for: Process" href="/track/silicon-scally/process/" class="tracklisttrackname mx-link">Process</a><div data-url="/track/silicon-scally/process/buylinks/" class="mx-link tracklistbuylinks">Buy</div><div class="clearit"></div><span class="buylinks-placeholder"></span><div class="clearit"></div><div class="clearit"></div><a title="Go to artist page for: Silicon Scally" href="/artist/silicon-scally/" class="tracklistartistname mx-link">Silicon Scally</a><div class="clearit"></div></td><td class="section-number-cell">' +
'9' +
'</td></tr><tr class="section-row-track"><td class="tracklistcell"><a title="Go to track page for: Space Booty" href="/track/dexter/space-booty/" class="tracklisttrackname mx-link">Space Booty</a><div data-url="/track/dexter/space-booty/buylinks/" class="mx-link tracklistbuylinks">Buy</div><div class="clearit"></div><span class="buylinks-placeholder"></span><div class="clearit"></div><div class="clearit"></div><a title="Go to artist page for: Dexter" href="/artist/dexter/" class="tracklistartistname mx-link">Dexter</a><div class="clearit"></div></td><td class="section-number-cell">' +
'10' +
'</td></tr><tr class="section-row-track"><td class="tracklistcell"><a title="Go to track page for: Feathers (Radioactive Man Remix)  []" href="/track/meat-katie-aquasky/feathers-radioactive-man-remix/" class="tracklisttrackname mx-link">Feathers (Radioactive Man Remix)  []</a><div data-url="/track/meat-katie-aquasky/feathers-radioactive-man-remix/buylinks/" class="mx-link tracklistbuylinks">Buy</div><div class="clearit"></div><span class="buylinks-placeholder"></span><div class="clearit"></div><div class="clearit"></div><a title="Go to artist page for: Meat Katie &amp; Aquasky" href="/artist/meat-katie-aquasky/" class="tracklistartistname mx-link">Meat Katie &amp; Aquasky</a><div class="clearit"></div></td><td class="section-number-cell">' +
'11' +
'</td></tr><tr class="section-row-track"><td class="tracklistcell"><a title="Go to track page for: Punkadelic (Radioactive Man Remix)" href="/track/freq-nasty/punkadelic-radioactive-man-remix/" class="tracklisttrackname mx-link">Punkadelic (Radioactive Man Remix)</a><div data-url="/track/freq-nasty/punkadelic-radioactive-man-remix/buylinks/" class="mx-link tracklistbuylinks">Buy</div><div class="clearit"></div><span class="buylinks-placeholder"></span><div class="clearit"></div><div class="clearit"></div><a title="Go to artist page for: Freq Nasty" href="/artist/freq-nasty/" class="tracklistartistname mx-link">Freq Nasty</a><div class="clearit"></div></td><td class="section-number-cell">' +
'12' +
'</td></tr><tr class="section-row-track"><td class="tracklistcell"><a title="Go to track page for: Pieces Of Eight (Diverted Remix)" href="/track/radioactive-man/pieces-of-eight-diverted-remix/" class="tracklisttrackname mx-link">Pieces Of Eight (Diverted Remix)</a><div data-url="/track/radioactive-man/pieces-of-eight-diverted-remix/buylinks/" class="mx-link tracklistbuylinks">Buy</div><div class="clearit"></div><span class="buylinks-placeholder"></span><div class="clearit"></div><div class="clearit"></div><a title="Go to artist page for: Radioactive Man" href="/artist/radioactive-man/" class="tracklistartistname mx-link">Radioactive Man</a><div class="clearit"></div></td><td class="section-number-cell">' +
'13' +
'</td></tr><tr class="section-row-track"><td class="tracklistcell"><a title="Go to track page for: Blue Flashing Lights" href="/track/xxxy/blue-flashing-lights/" class="tracklisttrackname mx-link">Blue Flashing Lights</a><div data-url="/track/xxxy/blue-flashing-lights/buylinks/" class="mx-link tracklistbuylinks">Buy</div><div class="clearit"></div><span class="buylinks-placeholder"></span><div class="clearit"></div><div class="clearit"></div><a title="Go to artist page for: Xxxy" href="/artist/xxxy/" class="tracklistartistname mx-link">Xxxy</a><div class="clearit"></div></td><td class="section-number-cell">' +
'14' +
'</td></tr><tr class="section-row-track"><td class="tracklistcell"><a title="Go to track page for: Fat Skinny People" href="/track/dexter/fat-skinny-people/" class="tracklisttrackname mx-link">Fat Skinny People</a><div data-url="/track/dexter/fat-skinny-people/buylinks/" class="mx-link tracklistbuylinks">Buy</div><div class="clearit"></div><span class="buylinks-placeholder"></span><div class="clearit"></div><div class="clearit"></div><a title="Go to artist page for: Dexter" href="/artist/dexter/" class="tracklistartistname mx-link">Dexter</a><div class="clearit"></div></td><td class="section-number-cell">' +
'15' +
'</td></tr><tr class="section-row-track"><td class="tracklistcell"><a title="Go to track page for: Beyond Perversion (Posthuman Remix)" href="/track/debasser/beyond-perversion-posthuman-remix/" class="tracklisttrackname mx-link">Beyond Perversion (Posthuman Remix)</a><div data-url="/track/debasser/beyond-perversion-posthuman-remix/buylinks/" class="mx-link tracklistbuylinks">Buy</div><div class="clearit"></div><span class="buylinks-placeholder"></span><div class="clearit"></div><div class="clearit"></div><a title="Go to artist page for: Debasser" href="/artist/debasser/" class="tracklistartistname mx-link">Debasser</a><div class="clearit"></div></td><td class="section-number-cell">' +
'16' +
'</td></tr></tbody></table></body></html>';
